//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string BindPhone { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string FatherName { get; set; }
        public string FatherContract { get; set; }
        public string MotherName { get; set; }
        public string MotherContract { get; set; }
        public string Address { get; set; }
        public string Wechart { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatorId { get; set; }
        public string UpdatorId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string DeletorId { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string BindAccount { get; set; }
    }
}
