//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ButtonGroup
    {
        public int BG_Id { get; set; }
        public string BG_Name { get; set; }
        public string BG_Name_En { get; set; }
        public string BG_Desc { get; set; }
        public Nullable<int> BG_OrderIndex { get; set; }
        public Nullable<bool> BG_IsSuspended { get; set; }
        public string BG_Mark { get; set; }
        public string BG_CreatedBy { get; set; }
        public Nullable<System.DateTime> BG_CreatedOn { get; set; }
        public string BG_LastUpdBy { get; set; }
        public Nullable<System.DateTime> BG_LastUpdOn { get; set; }
        public byte[] BG_RowVersion { get; set; }
    }
}
