//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Button
    {
        public SYS_Button()
        {
            this.SYS_FunctionItem = new HashSet<SYS_FunctionItem>();
        }
    
        public int BTN_Id { get; set; }
        public string BTN_Name { get; set; }
        public string BTN_Name_En { get; set; }
        public string BTN_Desc { get; set; }
        public int BTN_OrderIndex { get; set; }
        public bool BTN_IsSuspended { get; set; }
        public string BTN_Mark { get; set; }
        public string BTN_CreatedBy { get; set; }
        public System.DateTime BTN_CreatedOn { get; set; }
        public string BTN_LastUpdBy { get; set; }
        public Nullable<System.DateTime> BTN_LastUpdOn { get; set; }
        public byte[] BTN_RowVersion { get; set; }
    
        public virtual ICollection<SYS_FunctionItem> SYS_FunctionItem { get; set; }
    }
}
