//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Company
    {
        public string COMP_Code { get; set; }
        public string COMP_Name_1 { get; set; }
        public string COMP_Name_2 { get; set; }
        public string COMP_Name_3 { get; set; }
        public string COMP_Address_1 { get; set; }
        public string COMP_Address_2 { get; set; }
        public string COMP_Address_3 { get; set; }
        public string COMP_DeliveryName_1 { get; set; }
        public string COMP_DeliveryName_2 { get; set; }
        public string COMP_DeliveryName_3 { get; set; }
        public string COMP_DeliveryAddress_1 { get; set; }
        public string COMP_DeliveryAddress_2 { get; set; }
        public string COMP_DeliveryAddress_3 { get; set; }
        public string COMP_TaxCode { get; set; }
        public string COMP_BankName { get; set; }
        public string COMP_BankAccount { get; set; }
        public string COMP_Tel { get; set; }
        public string COMP_Fax { get; set; }
        public byte COMP_FiscalMonStart { get; set; }
        public byte COMP_FiscalMonEnd { get; set; }
        public Nullable<short> COMP_LastCalCostYear { get; set; }
        public Nullable<byte> COMP_LastCalCostMonth { get; set; }
        public byte[] COMP_RowVersion { get; set; }
    }
}
