//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_SystemRole
    {
        public SYS_SystemRole()
        {
            this.SYS_AccountRole = new HashSet<SYS_AccountRole>();
            this.SYS_RoleFunction = new HashSet<SYS_RoleFunction>();
        }
    
        public int ROLE_Id { get; set; }
        public string ROLE_Name { get; set; }
        public string ROLE_Name_En { get; set; }
        public int ROLE_Level { get; set; }
        public string ROLE_Desc { get; set; }
        public int ROLE_OrderIndex { get; set; }
        public bool ROLE_IsSuspended { get; set; }
        public string ROLE_Mark { get; set; }
        public string ROLE_CreatedBy { get; set; }
        public System.DateTime ROLE_CreatedOn { get; set; }
        public string ROLE_LastUpdBy { get; set; }
        public Nullable<System.DateTime> ROLE_LastUpdOn { get; set; }
        public byte[] ROLE_RowVersion { get; set; }
    
        public virtual ICollection<SYS_AccountRole> SYS_AccountRole { get; set; }
        public virtual ICollection<SYS_RoleFunction> SYS_RoleFunction { get; set; }
    }
}
