//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AccountRole
    {
        public string staffid { get; set; }
        public string status { get; set; }
        public bool issuspend { get; set; }
        public int ROLE_Id { get; set; }
        public string ROLE_Name { get; set; }
        public string ROLE_Name_En { get; set; }
        public int ROLE_Level { get; set; }
        public int ACC_Id { get; set; }
    }
}
