//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Dics
    {
        public string Dics_Code { get; set; }
        public string Title { get; set; }
        public Nullable<int> Sortnum { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string DicCategoryTitle { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Code { get; set; }
    }
}
