//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FunctionItem
    {
        public int FI_TreeId { get; set; }
        public string FT_Name { get; set; }
        public int FI_ButtonGroupId { get; set; }
        public string BG_Name { get; set; }
        public int FI_ButtonId { get; set; }
        public int FI_Id { get; set; }
        public string BTN_Name { get; set; }
        public Nullable<int> FI_ButtonGroupOrderIndex { get; set; }
        public Nullable<int> FI_ButtonOrderIndex { get; set; }
    }
}
