//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RoleFunctionItem
    {
        public string ROLE_Name { get; set; }
        public int RF_Id { get; set; }
        public int FI_TreeId { get; set; }
        public string FT_Name { get; set; }
        public string FT_Desc { get; set; }
        public Nullable<int> FT_OrderIndex { get; set; }
        public Nullable<int> FT_ParentId { get; set; }
        public string BG_Name { get; set; }
        public string BTN_Name { get; set; }
        public string BG_Name_En { get; set; }
        public string BTN_Name_En { get; set; }
        public string FT_Name_En { get; set; }
        public string ROLE_Name_En { get; set; }
        public string FT_FormNameOrUrl { get; set; }
        public Nullable<bool> FT_IsSuspended { get; set; }
    }
}
